version: "3.7"

services:

  postgres:
    image: "postgres:13"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - db:/data/postgres

  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: hw17-app:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
  db: